### ISSUE TITLE
[FR] Ability to edit macros

### ISSUE THREAD

**Issue by chronos1970** [AllanChain/logseq-live-math#33]
The ability to edit existing (default) macros and define new macros can be quite handy for advanced users. Furthermore, there are many default macros in MathLive that don't work well in KaTex. For instance, typing `\phase{30}` gets converted into `\enclose{phasorangle}[shadow="none", solid currentColor]{30}` which doesn't display in KaTex. Another example is `\mathbf{\dot{x}}` which gets converted into `\bm{\dot{x}}`. I don't know if MathLive even recognizes `\phasor{}` as a command. But it shouldn't expand it into an unsupported macro.

A possible solution is to provide a way to define aliases for certain commands to improve compatibility between MathLive and KaTex. Allowing us, for instance, to use `\phasor{}` and MathLive would display it internally using `\enclose{phasorangle}[shadow="none", solid currentColor]{30}`. I do acknowledge, however, that such a solution would be quite _hacky_.

**Comment by AllanChain** [comment]
I've added the settings to configure MathLive macros.

If MathLive does not have [this bug](https://github.com/arnog/mathlive/issues/1565), we can have everything work properly by setting `expand: false` for each macro supported by KaTeX. In your case, it is
```json
    "phase": {
      "def": "\\enclose{phasorangle}{#1}",
      "args": 1,
      "captureSelection": false,
      "expand": false
    }
```
And the final result is just `$\phase{30}`. However, because of that bug, you can not edit number `30` inside that angle in MathLive afterward. But at least it is better than before.
